"""YAML config parser. Reads config generated by Next.js Wizard."""

import os
import yaml
from pathlib import Path
from .types import BuildConfig
from .errors import ConfigError


def load_config(config_path: str, output_dir: str) -> BuildConfig:
    path = Path(config_path)
    if not path.exists():
        raise ConfigError(f"Config not found: {config_path}")

    with open(path, 'r', encoding='utf-8') as f:
        raw = yaml.safe_load(f) or {}

    if not isinstance(raw, dict):
        raise ConfigError(f"Invalid config format: {config_path}")

    # Auto-discover transcripts from uploads dir
    upload_dir = Path(output_dir).parent / "uploads"
    transcript_paths = []
    if upload_dir.exists():
        transcript_paths = sorted(
            str(p) for p in upload_dir.glob("*")
            if p.suffix in ('.txt', '.md', '.srt', '.vtt')
        )
    # Also check output dir itself for uploaded files
    for p in Path(output_dir).glob("*.txt"):
        if str(p) not in transcript_paths:
            transcript_paths.append(str(p))

    tier_map = {"draft": "draft", "standard": "standard", "premium": "premium"}

    return BuildConfig(
        name=raw.get("name", "Untitled"),
        domain=raw.get("domain", "custom"),
        language=raw.get("language", "vi"),
        quality_tier=tier_map.get(raw.get("quality_tier", "standard"), "standard"),
        platforms=raw.get("platforms", ["claude"]),
        baseline_sources=raw.get("baseline_sources", []),
        transcript_paths=transcript_paths,
        output_dir=output_dir,
        config_path=config_path,
        claude_api_key=os.environ.get("CLAUDE_API_KEY", ""),
        claude_model=os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-20250514"),
        seekers_cache_dir=os.environ.get("SEEKERS_CACHE_DIR", "./data/cache"),
        seekers_cache_ttl_hours=int(os.environ.get("SEEKERS_CACHE_TTL_HOURS", "168")),
    )


def get_tier_params(tier: str) -> dict:
    return {
        "draft": {"max_atoms_per_chunk": 20, "verify_sample_pct": 30, "dedup_threshold": 0.7},
        "standard": {"max_atoms_per_chunk": 15, "verify_sample_pct": 70, "dedup_threshold": 0.8},
        "premium": {"max_atoms_per_chunk": 10, "verify_sample_pct": 100, "dedup_threshold": 0.9},
    }.get(tier, {"max_atoms_per_chunk": 15, "verify_sample_pct": 70, "dedup_threshold": 0.8})
