/**
 * Generates a YAML config string from wizard form data.
 * Used when user fills out the Build Wizard instead of uploading raw YAML.
 */

export interface WizardConfig {
  name: string;
  domain: string;
  language: string;
  quality_tier: string;
  platforms: string[];
  baseline_urls: string[];
  description?: string;
}

export function generateConfigYaml(config: WizardConfig): string {
  const lines: string[] = [];

  lines.push(`# Auto-generated by Skill Factory Web`);
  lines.push(`# ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`name: ${config.name}`);
  lines.push(`domain: ${config.domain}`);
  lines.push(`language: ${config.language || "vi"}`);
  lines.push(`quality_tier: ${config.quality_tier || "standard"}`);

  if (config.description) {
    lines.push(`description: "${config.description}"`);
  }

  if (config.platforms && config.platforms.length > 0) {
    lines.push(`platforms: [${config.platforms.join(", ")}]`);
  } else {
    lines.push(`platforms: [claude]`);
  }

  if (config.baseline_urls && config.baseline_urls.length > 0) {
    lines.push(``);
    lines.push(`baseline_sources:`);
    for (const url of config.baseline_urls) {
      const trimmed = url.trim();
      if (!trimmed) continue;
      lines.push(`  - url: ${trimmed}`);
      lines.push(`    type: documentation`);
    }
  } else {
    lines.push(`baseline_sources: []`);
  }

  return lines.join("\n") + "\n";
}

export function mergeTemplateConfig(templateYaml: string, overrides: Partial<WizardConfig>): string {
  let result = templateYaml;

  if (overrides.name) {
    result = result.replace(/^name:.*$/m, `name: ${overrides.name}`);
  }
  if (overrides.language) {
    result = result.replace(/^language:.*$/m, `language: ${overrides.language}`);
  }
  if (overrides.quality_tier) {
    result = result.replace(/^quality_tier:.*$/m, `quality_tier: ${overrides.quality_tier}`);
  }

  return result;
}
