/**
 * Generates a YAML config string from wizard form data.
 * Used when user fills out the Build Wizard instead of uploading raw YAML.
 */

export interface WizardConfig {
  name: string;
  domain: string;
  language: string;
  quality_tier: string;
  platforms: string[];
  baseline_urls: string[];
  seekers_output_dir?: string;
  description?: string;
  github_repo?: string;
  github_analyze_code?: boolean;
}

/** Escape YAML string value — quote if it contains special chars */
function yamlStr(val: string): string {
  if (/[:#{}[\],&*?|>!%@`"']/.test(val) || val.trim() !== val) {
    return `"${val.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return val;
}

export function generateConfigYaml(config: WizardConfig): string {
  const lines: string[] = [];

  lines.push(`# Auto-generated by Skill Factory Web`);
  lines.push(`# ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`name: ${yamlStr(config.name)}`);
  lines.push(`domain: ${yamlStr(config.domain)}`);
  lines.push(`language: ${yamlStr(config.language || "vi")}`);
  lines.push(`quality_tier: ${config.quality_tier || "standard"}`);

  if (config.description) {
    lines.push(`description: ${yamlStr(config.description)}`);
  }

  // Platforms — MUST be block array format
  lines.push(`platforms:`);
  const platforms = config.platforms?.length ? config.platforms : ["claude"];
  for (const p of platforms) {
    lines.push(`  - ${p}`);
  }

  // Fields required by Python BuildConfig
  lines.push(`transcript_paths: []`);
  lines.push(`output_dir: "./output"`);
  lines.push(`seekers_output_dir: ${yamlStr(config.seekers_output_dir || "")}`);
  lines.push(`claude_model: "claude-sonnet-4-20250514"`);

  // GitHub repo analysis
  lines.push(`github_repo: ${yamlStr(config.github_repo || "")}`);
  lines.push(`github_analyze_code: ${config.github_analyze_code !== false}`);

  // Baseline sources (URLs for web scraping)
  if (config.baseline_urls && config.baseline_urls.length > 0) {
    lines.push(``);
    lines.push(`baseline_sources:`);
    for (const url of config.baseline_urls) {
      const trimmed = url.trim();
      if (!trimmed) continue;
      lines.push(`  - url: ${trimmed}`);
      lines.push(`    type: documentation`);
    }
  } else {
    lines.push(`baseline_sources: []`);
  }

  return lines.join("\n") + "\n";
}

export function mergeTemplateConfig(templateYaml: string, overrides: Partial<WizardConfig>): string {
  let result = templateYaml;

  if (overrides.name) {
    result = result.replace(/^name:.*$/m, `name: ${yamlStr(overrides.name)}`);
  }
  if (overrides.language) {
    result = result.replace(/^language:.*$/m, `language: ${yamlStr(overrides.language)}`);
  }
  if (overrides.quality_tier) {
    result = result.replace(/^quality_tier:.*$/m, `quality_tier: ${overrides.quality_tier}`);
  }
  if (overrides.platforms?.length) {
    const blockPlatforms = overrides.platforms.map(p => `  - ${p}`).join("\n");
    result = result.replace(/^platforms:.*$/m, `platforms:\n${blockPlatforms}`);
  }

  return result;
}
